### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by Bowen-cq** [wangle53/CSA-CDGAN#2]
请问作者可以分享一下论文的下载地址吗？我找了好久没有找到，谢谢！

**Comment by wangle53** [comment]
您好，文章已经被接收，但还未见刊，后续将更新链接。方便的话可以留个邮箱，我发一份手稿给您。

**Comment by lanfeiwuwudibang** [comment]
> 
您好，我也想阅读一下您的手稿，方便给我发一份吗?（我的邮箱：1061969834@qq.com）

**Comment by xjh0929** [comment]
作者，您好，请问我想引用您的文献，引用格式怎么写呢？另外希望可以阅读您的手稿（我得邮箱 xingjh0929@163.com）
