### ISSUE TITLE
Use this method in scene change detection.

### ISSUE THREAD

**Issue by WangDeyu** [wangle53/CSA-CDGAN#4]
Did you try this method in scene change detection like (VL_CMU_CD, etc.). Compared with transCD, which one can get better result?

**Comment by wangle53** [comment]
I didn't. Samples in VL_CMU_CD have large view point difference, i'm not sure if csa-cdgan will get good performance. But it is very nice if you can try.

**Comment by WangDeyu** [comment]
Thank you for your reply!
